In [14]:
import numpy as np

# Create a 2D array of shape 5x5 with all zeros and 1 on the border
x = np.ones((5,5))
x[1:4, 1:4] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
# Create a 2D array of shape 5x5 with all zeros and 1 on the diagonal
x = np.zeros((5,5))
np.fill_diagonal(x, 1)
print(x)
np.eye(5)
np.identity(5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
# Write a function that takes 2 arrays (A and B) as an input and return the element-wise square of the dot product of two input vectors
x1 = np.random.randint(10, size=5)
print(x1)
x2 = np.random.randint(10, size=5)
print(x2)
def get_element_wise_square(a, b):
    return np.square(np.dot(a, b))
print(get_element_wise_square(x1, x2))

169989444


In [31]:
# Write a function that takes 2 arrays (A and B) of the same shape as in input and return the following:
# - The element-wise square of sum A and B
# - The element-wise square of difference of A and B
# - The sum of element-wise square of A and B
# - The difference of element-wise square of A and B
x1 = np.random.randint(10, size=5)
print(x1)
x2 = np.random.randint(10, size=5)
print(x2)
def work_with_arrays(a, b):
    if a.shape != b.shape:
        return 'error'

    task_a = np.square(np.add(a, b))
    print(task_a)

    task_b = np.square(np.subtract(a, b))
    print(task_b)

    task_c = np.add(np.square(a), np.square(b))
    print(task_c)

    task_d = np.subtract(np.square(a), np.square(b))
    print(task_d)

work_with_arrays(x1, x2)

[9 7 8 3 5]
[1 5 7 0]


'error'